# Generated by Django 3.2.5 on 2022-01-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_name_callbackrequest_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callbackrequest',
            old_name='username',
            new_name='name',
        ),
    ]
