# Generated by Django 3.2.5 on 2022-01-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_callbackrequest_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
