# Generated by Django 3.2.5 on 2022-01-20 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_callbackrequest_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
