# Generated by Django 3.2.5 on 2022-01-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220120_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='id_number',
            field=models.IntegerField(max_length=8, unique=True),
        ),
    ]
